version: 3

silent: true

includes:
  cloud: ./ops/taskfile.cloud.yaml
  local: ./ops/taskfile.local.yaml

tasks:
  init:
    desc: initialise local environment
    cmds:
      - task: pre-commit
      - task: installs
      - task: todo

  pre-commit:
    desc: initialises pre-commit hooks
    cmds:
      - pre-commit autoupdate &>/dev/null &
      - pre-commit install install &>/dev/null &

  installs:
    desc: installs packages
    cmds:
      - pip install -r .devcontainer/requirements.txt
      - go install github.com/charmbracelet/glow@latest

  pre-commit:run:
    desc: run pre-commit hooks
    deps: ["pre-commit:init"]
    cmds:
      - pre-commit run --all-files

  todo:
    desc: show to do list to
    cmds:
      - glow TODO.md
    preconditions:
      - stat TODO.md
