version: 3

includes:
  cloud: ./ops/taskfile.cloud.yaml
  local: ./ops/taskfile.local.yaml

tasks:
  init:
    desc: initialise local environment
    cmds:
      - tfenv pin
      - task: pre-commit:init
      - task: pre-commit:run

  rename:
    desc: change repo name in readme.md
    cmds:
      - sed -i '' s/$TEMPLATE_NAME/$REQUIRED_NAME/g README.md

  pre-commit:init:
    desc: initialises pre-commit hooks
    cmds:
      - pre-commit autoupdate
      - git add .
      - pre-commit install

  pre-commit:run:
    desc: runs all pre-commit hooks
    cmds:
      - pre-commit run --all-files
