version: 3

includes:
  cloud: ./ops/taskfile.cloud.yaml
  local: ./ops/taskfile.local.yaml

tasks:
  init:
    desc: initialise local environment
    cmds:
      - task: terraform:pin
      - task: pre-commit:init
      - task: todo

  terraform:pin:
    desc: pins required version of terraform
    silent: true
    cmds:
      - tfenv pin

  pre-commit:init:
    desc: initialises pre-commit hooks
    silent: true
    cmds:
      - pre-commit install

  todo:
    desc: show to do list to
    cmds:
      - cat ./.todo
