name: "tfsec IaC Scan"
on:
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: '0 0 * * *'
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
